sudo: false

language: cpp

addons: &addons
  apt:
    packages: timeout
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.9

cache:
  apt: true
  ccache: true
#  directories:
#    - $BUILD_DEPS


# Do not build our sync branch.
branches:
  only:
    - master
    - "*Travis*"

# Without the top-level env, no job will be allowed to fail.
env:

matrix:
  include:
    # There seems to be a hard limit to how many machines a Travis build will
    # across all platforms. By interleaving OS X, the hope is to get in the
    # queue faster while not blocking Linux builds from occuring.
    - compiler: clang
      addons:
        apt:
          sources: *sources
          packages: ['lcov']
      env: COMPILER=g++ C_COMPILER=gcc BUILD_TYPE=Coverage

install:
  - |
    if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
       PATH=~/.local/bin:${PATH};
       pip install --user --upgrade pip;
       pip install --user cpp-coveralls;
    fi

script:
- echo "Downloading Latest ROOT binaries."
- |
  mkdir ../root/
  d=$(date +%a)
  for i in `seq 1 7`; do
    if [[ curl -s --head http://lcgpackages.web.cern.ch/lcgpackages/tarFiles/nightlies/rootcov/$d ]]; then
       echo "Downloading and untaring $ROOT_TAR"
       ROOT_TAR=http://lcgpackages.web.cern.ch/lcgpackages/tarFiles/nightlies/rootcov/$d/ROOT-HEAD_a512e-x86_64-ubuntu1404-gcc48-opt.tgz
       cd ../root/
       curl $ROOT_TAR | tar xvz
       ls -la
       source bin/thisroot.sh
       cd -
       break;
    fi
    d=$(date +%a -d "$d - 1 day")
  done;



on_failure:
  -|
  echo "Showing current directory contents"
  ls -la
